# -*- coding: utf-8 -*-
"""DSC MiniProject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-tZ2J9L9UiMRkWdZTem9PmytGEce8LJ

1. IMPORT LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""2. LOAD DATASET"""

df = pd.read_csv("openfoodfacts_nutrition_final_2025-12-10.csv")

df.head()

print(df.info())

"""3. DATA CLEANING

🔹 Missing Values
"""

print(df.isnull().sum())
df = df.dropna()

"""🔹 Duplicate Values"""

df = df.drop_duplicates().sum()

"""4. SELECT RELEVANT COLUMNS"""

df = df[['energy-kcal_100g', 'fat_100g', 'carbohydrates_100g',
         'proteins_100g', 'sugars_100g']]

df = df[['energy-kcal_100g', 'fat_100g', 'carbohydrates_100g',
         'proteins_100g', 'sugars_100g']]


print(df.head())

df_encoded = pd.get_dummies(df, drop_first=True)

df_encoded.head()

"""5. STATISTICAL SUMMARY"""

print(df.describe())

"""6. CORRELATION ANALYSIS"""

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

"""7. HISTOGRAM (EDA)"""

df.hist(figsize=(10,8))
plt.suptitle("Histogram of Features")
plt.show()

"""8. BAR GRAPH"""

df.groupby('proteins_100g')['energy-kcal_100g'].mean().plot(kind='bar')
plt.title("Average Calories by Protein")
plt.xlabel("Protein (g)")
plt.ylabel("Calories (kcal)")
plt.show()

"""9. SKEWNESS"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15,10))

numeric_cols = df.columns.tolist()
for i, col in enumerate(numeric_cols[:6]):  # first 6 columns
    plt.subplot(2, 3, i+1)
    sns.histplot(df[col], kde=True)
    plt.title(f"Distribution of {col}")

plt.tight_layout()
plt.show()

"""10. KURTOSIS"""

plt.figure(figsize=(10,6))

for col in df.columns:
    k = df[col].kurtosis()

    # classify
    if k > 3:
        label_type = "Leptokurtic"
        style = '--'
    elif k < 3:
        label_type = "Platykurtic"
        style = ':'
    else:
        label_type = "Mesokurtic"
        style = '-'

    # plot KDE curve
    sns.kdeplot(df[col], linestyle=style, linewidth=2,
                label=f"{label_type} ({col})")

plt.title("Kurtosis Types from Dataset (Multiple Features)")
plt.xlabel("Values")
plt.ylabel("Density")
plt.legend()
plt.grid()
lepto = []
meso = []
platy = []

for col in df.columns:
    k = df[col].kurtosis()

    if k > 3:
        lepto.append(col)
    elif k < 3:
        platy.append(col)
    else:
        meso.append(col)

print("Leptokurtic:", lepto)
print("Mesokurtic:", meso)
print("Platykurtic:", platy)
plt.show()

"""11. Z-TEST (OUTLIER DETECTION)"""

z_scores = np.abs(zscore(df))
print(z_scores)

# Remove outliers
df_clean = df[(z_scores < 3).all(axis=1)]

"""12. TRAIN-TEST SPLIT (80-20)"""

X = df_clean[['fat_100g', 'carbohydrates_100g', 'proteins_100g', 'sugars_100g']]
y = df_clean['energy-kcal_100g']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

future_data = X_test.head(5)

future_predictions = model.predict(future_data)

future_df = future_data.copy()
future_df['Predicted Calories'] = future_predictions.round(2)

print(future_df)

"""13. MACHINE LEARNING MODEL"""

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

plt.figure(figsize=(10,5))

plt.plot(y_test.values, label="Actual Values", color='blue')
plt.plot(y_pred, label="Predicted Values", linestyle='dashed', color='red')

plt.title("Actual vs Predicted Values (Comparison)")
plt.xlabel("Data Points")
plt.ylabel("Calories")

plt.legend()
plt.grid()

plt.show()

features = X.columns

plt.figure(figsize=(12,8))

for i, col in enumerate(features):
    plt.subplot(2,2,i+1)

    plt.scatter(X_test[col], y_test, color='blue')

    # regression line
    m, b = np.polyfit(X_test[col], y_test, 1)
    plt.plot(X_test[col], m*X_test[col] + b, color='red')

    plt.title(f"{col} vs Calories")
    plt.xlabel(col)
    plt.ylabel("Calories")

plt.tight_layout()
plt.show()

"""14. MODEL EVALUATION"""

print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

"""15. PREDICTION GRAPH"""

plt.scatter(y_test, y_pred)
plt.xlabel("Actual Calories")
plt.ylabel("Predicted Calories")
plt.title("Actual vs Predicted")
plt.show()